export default function handler(req, res) {
  res.status(200).json({
    data: [
      {
        id: "1",
        type: "data",
        attributes: {
          createdAt: "2024-05-23T04:47:21.000Z",
          updatedAt: "2024-05-23T04:47:21.000Z",
          active: true,
          project_id: 200001,
          creator_id: 567,
          description: "This is a dummy description for item 1",
          amount: 345.67,
          status: "pending",
          notes: [
            "This is note 1 for this item",
            "This is another note for item 1",
          ],
          increaase_budget: false,
          payment_terms: "Net 30 days",
          reviewed_by: 890,
          approved_by: null,
          document_urls: [
            "https://www.example.com/document1.pdf",
            "https://www.example.com/document2.docx",
          ],
        },
      },
      {
        id: "2",
        type: "data",
        attributes: {
          createdAt: "2024-05-23T04:47:21.000Z",
          updatedAt: "2024-05-23T04:47:21.000Z",
          active: false,
          project_id: 200001,
          creator_id: 234,
          description: "This is a dummy description for item 2",
          amount: 879.21,
          status: "approved",
          notes: [
            "This is note 2 for this item",
            "This is another note for item 2",
          ],
          increaase_budget: true,
          payment_terms: "Net 30 days",
          reviewed_by: 123,
          approved_by: 789,
          document_urls: [
            "https://www.example.com/document1.pdf",
            "https://www.example.com/document2.docx",
          ],
        },
      },
      {
        id: "3",
        type: "data",
        attributes: {
          createdAt: "2024-05-23T04:47:21.000Z",
          updatedAt: "2024-05-23T04:47:21.000Z",
          active: true,
          project_id: 200001,
          creator_id: 987,
          description: "This is a dummy description for item 3",
          amount: 123.45,
          status: "rejected",
          notes: [
            "This is note 3 for this item",
            "This is another note for item 3",
          ],
          increaase_budget: false,
          payment_terms: "Net 30 days",
          reviewed_by: 654,
          approved_by: null,
          document_urls: [
            "https://www.example.com/document1.pdf",
            "https://www.example.com/document2.docx",
          ],
        },
      },
      {
        id: "4",
        type: "data",
        attributes: {
          createdAt: "2024-05-23T04:47:21.000Z",
          updatedAt: "2024-05-23T04:47:21.000Z",
          active: true,
          project_id: 200001,
          creator_id: 345,
          description: "This is a dummy description for item 4",
          amount: 456.78,
          status: "pending",
          notes: [
            "This is note 4 for this item",
            "This is another note for item 4",
          ],
          increaase_budget: true,
          payment_terms: "Net 30 days",
          reviewed_by: 234,
          approved_by: 567,
          document_urls: [
            "https://www.example.com/document1.pdf",
            "https://www.example.com/document2.docx",
          ],
        },
      },
      {
        id: "5",
        type: "data",
        attributes: {
          createdAt: "2024-05-23T04:47:21.000Z",
          updatedAt: "2024-05-23T04:47:21.000Z",
          active: false,
          project_id: 200001,
          creator_id: 678,
          description: "This is a dummy description for item 5",
          amount: 789.01,
          status: "approved",
          notes: [
            "This is note 5 for this item",
            "This is another note for item 5",
          ],
          increaase_budget: false,
          payment_terms: "Net 30 days",
          reviewed_by: 345,
          approved_by: 678,
          document_urls: [
            "https://www.example.com/document1.pdf",
            "https://www.example.com/document2.docx",
          ],
        },
      },
      {
        id: "6",
        type: "data",
        attributes: {
          createdAt: "2024-05-23T04:47:21.000Z",
          updatedAt: "2024-05-23T04:47:21.000Z",
          active: true,
          project_id: 200001,
          creator_id: 456,
          description: "This is a dummy description for item 6",
          amount: 234.56,
          status: "rejected",
          notes: [
            "This is note 6 for this item",
            "This is another note for item 6",
          ],
          increaase_budget: true,
          payment_terms: "Net 30 days",
          reviewed_by: 456,
          approved_by: null,
          document_urls: [
            "https://www.example.com/document1.pdf",
            "https://www.example.com/document2.docx",
          ],
        },
      },
      {
        id: "7",
        type: "data",
        attributes: {
          createdAt: "2024-05-23T04:47:21.000Z",
          updatedAt: "2024-05-23T04:47:21.000Z",
          active: false,
          project_id: 200001,
          creator_id: 789,
          description: "This is a dummy description for item 7",
          amount: 890.12,
          status: "pending",
          notes: [
            "This is note 7 for this item",
            "This is another note for item 7",
          ],
          increaase_budget: false,
          payment_terms: "Net 30 days",
          reviewed_by: 567,
          approved_by: 890,
          document_urls: [
            "https://www.example.com/document1.pdf",
            "https://www.example.com/document2.docx",
          ],
        },
      },
      {
        id: "8",
        type: "data",
        attributes: {
          createdAt: "2024-05-23T04:47:21.000Z",
          updatedAt: "2024-05-23T04:47:21.000Z",
          active: true,
          project_id: 200001,
          creator_id: 890,
          description: "This is a dummy description for item 8",
          amount: 567.89,
          status: "approved",
          notes: [
            "This is note 8 for this item",
            "This is another note for item 8",
          ],
          increaase_budget: true,
          payment_terms: "Net 30 days",
          reviewed_by: 678,
          approved_by: 789,
          document_urls: [
            "https://www.example.com/document1.pdf",
            "https://www.example.com/document2.docx",
          ],
        },
      },
    ],
  });
}
